name: react CI
on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'SHA of the commit to deploy'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: npm test

